steps:

  ### Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/5asec-pos-web/feature:$SHORT_SHA'
      - '.'

  ### Publish
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/5asec-pos-web/feature:$SHORT_SHA'

  ### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"

        sed -i 's|gcr.io/PROJECT_ID/5asec-pos-web:.*|gcr.io/$PROJECT_ID/5asec-pos-web/feature:$SHORT_SHA|' ./kubernetes/deployments/*.yaml

#        kubectl apply --namespace ${_BRANCH_NAME} --recursive -f kubernetes/deployments
