steps:

  ### Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/google-demo:$SHORT_SHA'
      - '.'

  ### Publish
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/google-demo:$SHORT_SHA'

  ### Deploy
  - id: Deploy
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=reaktor-cluster'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        echo "Cluster: $${CLUSTER}"
        echo "Project: $${PROJECT}"
        echo "Zone: $${ZONE}"

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"

        IMAGE="gcr.io/$PROJECT_ID/google-demo:$SHORT_SHA"
        sed -i 's|gcr.io/PROJECT_ID/google-demo:.*|$${IMAGE}|' ./kubernetes/*.yaml
        kubectl apply --namespace google-demo --recursive -f kubernetes/
